//export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
//export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
//export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
